### ISSUE TITLE
Shift+click crash

### ISSUE THREAD

**Issue by Gegy** [MinerArcana/Runecarved#7]
```
java.lang.IndexOutOfBoundsException: Index: 37, Size: 37
	at java.util.ArrayList.rangeCheck(ArrayList.java:653)
	at java.util.ArrayList.get(ArrayList.java:429)
	at net.minecraft.inventory.Container.func_75135_a(Container.java:648)
	at com.minerarcana.runecarved.container.ContainerSimpleEnchanter.func_82846_b(ContainerSimpleEnchanter.java:295)
	at net.minecraft.inventory.Container.func_184996_a(Container.java:246)
	at net.minecraft.client.multiplayer.PlayerControllerMP.func_187098_a(PlayerControllerMP.java:566)
	at net.minecraft.client.gui.inventory.GuiContainer.func_184098_a(GuiContainer.java:638)
	at net.minecraft.client.gui.inventory.GuiContainer.func_73864_a(GuiContainer.java:392)
	at com.minerarcana.runecarved.gui.GuiSimpleEnchanter.func_73864_a(GuiSimpleEnchanter.java:92)
	at net.minecraft.client.gui.GuiScreen.func_146274_d(GuiScreen.java:533)
	at net.minecraft.client.gui.GuiScreen.func_146269_k(GuiScreen.java:501)
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1757)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1096)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:397)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
```
Occurred when transferring from enchantment slot to player inventory.

**Comment by FreneticScribbler** [comment]
Heh I always forget to fix shift click...
